# Generated by Django 5.1.4 on 2024-12-11 08:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_board_date_board_likes_board_reviews_board_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
