# Generated by Django 5.1.4 on 2024-12-11 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_board_create_at_board_update_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='board',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
